# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0002_author_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
